//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokWeb.Models.Entitiy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StokTakipEntities1 : DbContext
    {
        public StokTakipEntities1()
            : base("name=StokTakipEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArizaliUrun> ArizaliUrun { get; set; }
        public virtual DbSet<KategoriTablo> KategoriTablo { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Servis> Servis { get; set; }
        public virtual DbSet<StokGirisCikis> StokGirisCikis { get; set; }
        public virtual DbSet<StokTabloSatici> StokTabloSatici { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<WebUser> WebUser { get; set; }
    }
}
