//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokWeb.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class KategoriTablo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KategoriTablo()
        {
            this.StokTabloSatici = new HashSet<StokTabloSatici>();
        }
    
        public string KategoriNo { get; set; }
        public string Kategori { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StokTabloSatici> StokTabloSatici { get; set; }
    }
}
