//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokWeb.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servis
    {
        public int id { get; set; }
        public string Urun { get; set; }
        public string Gittigitarih { get; set; }
        public string GittigiServis { get; set; }
        public string GeldigiTarih { get; set; }
        public string TedenBolum { get; set; }
        public string Arıza { get; set; }
        public string Durum { get; set; }
        public string SicilNo { get; set; }
        public string YapılanIslem { get; set; }
    }
}
